In [121]:
# Create a 1D array of numbers from 0 to 9.
import numpy as np
import pandas as pd
import matplotlib as plt
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
#Create a 1D array of numbers from 0 to 9.
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Create a 3×3 numpy array of all True’s
arr1=np.ones((3,3))
print('Original Array : \n',arr1)


Original Array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr1>0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [63]:
#Given an array as input, print only odd numbers as output
arr2=np.array([[1,2,3],[7,8,9],[11,15,18]])
arr2

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [11, 15, 18]])

In [64]:
arr2_odd=arr2[np.where((arr2%2!=0))]
print(arr2_odd)

[ 1  3  7  9 11 15]


In [72]:
arr3_odd=np.where((arr2%2!=0))
arr2[arr3_odd]=-2
arr2

array([[-2,  2, -2],
       [-2,  8, -2],
       [-2, -2, 18]])

In [26]:
#How to reshape an array?
arr3=np.array([[1,2],[6,8],[5,10]])
print(arr3,arr3.shape)

[[ 1  2]
 [ 6  8]
 [ 5 10]] (3, 2)


In [30]:
print(arr3.reshape(2,3))

[[ 1  2  6]
 [ 8  5 10]]


In [41]:
#Convert a 1D array to a 2D array with 2 rows
arr4=np.arange(9)
print(arr4)

[0 1 2 3 4 5 6 7 8]


In [55]:
print(arr4.reshape(2,2))

[[0 1]
 [2 3]]


In [61]:
#Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 
a=np.arange(1,10)
print(a)
b=a[np.where((a%2!=0) | (a%4==0))]
print(b)

[1 2 3 4 5 6 7 8 9]
[1 3 4 5 7 8 9]


In [147]:
#Given array, check if there are any null values and print them out. 
x=np.array([10,11,12,15])
y=np.append(x,np.NaN)
print(y)

[10. 11. 12. 15. nan]


In [151]:
z=y[np.isnan(y)]
z

array([nan])

In [159]:
#How to replace all missing values with 0 in a numpy array?
import numpy as np
import pandas as pd
import matplotlib as plt
z=np.isnan((y))
p=np.where((z))
y[p]=0
y

array([10., 11., 12., 15.,  0.])

In [166]:
#How to find the count of each unique number in a NumPy array?
a=np.array([1,2,3,2,1,5,6,5,4,5])
u_values,u_counts=np.unique(a, return_counts=True)
u_values,u_counts

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 1, 1, 3, 1], dtype=int64))

In [175]:
#How to convert a numeric to a categorical (text) array?
fav_food_rating={1:'pizza',2:'burger',3:'sandwich',4:'choclates',5:'Icecream'}
text_array_rating=[]
for i in fav_food_rating:
    text_array_rating=np.append(text_array_rating, fav_food_rating[i])
text_array_rating

array(['pizza', 'burger', 'sandwich', 'choclates', 'Icecream'],
      dtype='<U32')

In [204]:
#Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 
a=np.arange(99,299)
for i in a:
    if ((i%5==0) & (i%7==0)):
        continue
    elif((i%5==0) | (i%7==0)):
        print(i)

100
110
112
115
119
120
125
126
130
133
135
145
147
150
154
155
160
161
165
168
170
180
182
185
189
190
195
196
200
203
205
215
217
220
224
225
230
231
235
238
240
250
252
255
259
260
265
266
270
273
275
285
287
290
294
295


In [249]:
#Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [250]:
j=-1
temp=[]
b=len(a)//2
for i in range(b):
    temp=a[i]
    a[i]=a[j]
    a[j]=temp
    j=j-1
print(a)

[19 18 17 16 15 14 13 12 11 10]
